### PR TITLE
More servers with Hidden Service. Certificate retrieval instructions.

### PR DESCRIPTION
**Pull request by dllud**
Since @chrisballinger mentioned that:

> we need a good list of servers for people to migrate.

I took the effort and searched the entire [XMPP Compliance Suite List](https://gultsch.de/compliance_ranked.html) for any servers with Tor Hidden Service that I had missed before. The full result is at [Public XMPP servers with Tor Hidden Service](https://gist.github.com/dllud/a46d4a555e31dfeff6ad41dcf20729ac). Here I am adding the new ones that have In-Band registration enabled: [jabjab.de](https://jabjab.de), [jabber.cat](https://jabber.cat), [chatme.im](https://chatme.im), [dismail.de](https://dismail.de), [hot-chilli.net](https://jabber.hot-chilli.net), [jabber.systemausfall.org](https://systemausfall.org/wikis/hilfe/Jabber), [im.koderoot.net](https://www.koderoot.net) and [evil.im](https://evil.im).

I've also added new instructions to the README on how to retrieve the certificate directly from the server, avoiding [xmpp.net which is currently offline](https://mail.jabber.org/pipermail/operators/2017-March/002956.html).

### CODE REVIEW

**Comment by chrisballinger** [comment]
Awesome, thank you! We need XEP-0357 and XEP-0363 for the clients to work properly, are you able to include those in the results? You can omit other extensions, these are really the only two that I think are fully required (we still disable XEP-0357 if an account is created over Tor though). I reopened issue #1

```json
{
"domain": "example.com",
"extensions": ["XEP-0357", "XEP-0363"]
}
```

**Comment by dllud** [comment]
Done.

**Comment by chrisballinger** [comment]
Great! I'll merge this and include in the next build.

One small request, when you include icons, could you make sure they are square-ish? It gets displayed in the UI with a 1:1 aspect ratio, and even if using aspect scaling it looks pretty weird.

**Comment by chrisballinger** [comment]
@dllud Just to double check, is the "server" entry the result of SRV lookup? Some servers have a domain of `example.com` and a server of `xmpp.example.com`. It was mainly there to make it possible for users to connect via Tor for servers without .onions because SRV lookups are not possible over Tor.  I should have documented this in the README, sorry.

**Comment by dllud** [comment]
Sorry, indeed I had it wrong in the newest entries. Thanks for the precious double-check. Pull request fixing this at #17.

**Pull request merged**
